// AUTO-GENERATED by scripts/gen-demo-catalog.ts — the clinic's real 29-lens
// IOL catalog (same data as supabase/seed.sql). Used only by the browser demo
// backend for the GitHub Pages deployment.
export type DemoLens = {
  id: string
  name: string
  type: string
  manufacturer: string
  model: string | null
  aConstant: number | null
}

export const DEMO_LENS_CATALOG: DemoLens[] = [
  {
    "id": "lens_naspro",
    "name": "NASPRO",
    "type": "MONOFOCAL",
    "manufacturer": "APPASAMY",
    "model": null,
    "aConstant": 118
  },
  {
    "id": "lens_supraphob",
    "name": "SUPRAPHOB",
    "type": "MONOFOCAL",
    "manufacturer": "APPASAMY",
    "model": null,
    "aConstant": 119.1
  },
  {
    "id": "lens_supraphob_toric",
    "name": "SUPRAPHOB TORIC",
    "type": "TORIC",
    "manufacturer": "APPASAMY",
    "model": null,
    "aConstant": 119.1
  },
  {
    "id": "lens_acrysof_sp",
    "name": "ACRYSOF SP",
    "type": "MONOFOCAL",
    "manufacturer": "ALCON",
    "model": null,
    "aConstant": 118.3
  },
  {
    "id": "lens_alcon_iq",
    "name": "ALCON IQ",
    "type": "MONOFOCAL",
    "manufacturer": "ALCON",
    "model": null,
    "aConstant": 118.7
  },
  {
    "id": "lens_clareon",
    "name": "CLAREON",
    "type": "MONOFOCAL",
    "manufacturer": "ALCON",
    "model": null,
    "aConstant": 118.8
  },
  {
    "id": "lens_panoptix",
    "name": "PANOPTIX",
    "type": "TRIFOCAL",
    "manufacturer": "ALCON",
    "model": null,
    "aConstant": 118.7
  },
  {
    "id": "lens_vivity_edof_",
    "name": "VIVITY (EDOF)",
    "type": "EDOF",
    "manufacturer": "ALCON",
    "model": null,
    "aConstant": 118.8
  },
  {
    "id": "lens_panoptix_toric",
    "name": "PANOPTIX TORIC",
    "type": "TORIC",
    "manufacturer": "ALCON",
    "model": null,
    "aConstant": 118.7
  },
  {
    "id": "lens_vivity_toric_edof_",
    "name": "VIVITY TORIC (EDOF)",
    "type": "TORIC",
    "manufacturer": "ALCON",
    "model": null,
    "aConstant": 118.8
  },
  {
    "id": "lens_clareon_toric",
    "name": "CLAREON TORIC",
    "type": "TORIC",
    "manufacturer": "ALCON",
    "model": null,
    "aConstant": 118.8
  },
  {
    "id": "lens_iq_toric",
    "name": "IQ TORIC",
    "type": "TORIC",
    "manufacturer": "ALCON",
    "model": null,
    "aConstant": 118.7
  },
  {
    "id": "lens_eyecryl_nat_hd",
    "name": "EYECRYL NAT HD",
    "type": "MONOFOCAL",
    "manufacturer": "BIOTECH",
    "model": null,
    "aConstant": 118.3
  },
  {
    "id": "lens_optiflex_trio",
    "name": "OPTIFLEX TRIO",
    "type": "TRIFOCAL",
    "manufacturer": "BIOTECH",
    "model": null,
    "aConstant": 118.6
  },
  {
    "id": "lens_eyecryl_activ",
    "name": "EYECRYL ACTIV",
    "type": "MONOFOCAL",
    "manufacturer": "BIOTECH",
    "model": null,
    "aConstant": 118
  },
  {
    "id": "lens_optiflex_trio_toric",
    "name": "OPTIFLEX TRIO TORIC",
    "type": "TORIC",
    "manufacturer": "BIOTECH",
    "model": null,
    "aConstant": 118.6
  },
  {
    "id": "lens_eyecryl_activ_bifocal_",
    "name": "EYECRYL ACTIV (BIFOCAL)",
    "type": "BIFOCAL",
    "manufacturer": "BIOTECH",
    "model": null,
    "aConstant": 118
  },
  {
    "id": "lens_eyecryl_toric_monofocal_",
    "name": "EYECRYL TORIC (MONOFOCAL)",
    "type": "TORIC",
    "manufacturer": "BIOTECH",
    "model": null,
    "aConstant": 118.5
  },
  {
    "id": "lens_magnus",
    "name": "MAGNUS",
    "type": "MONOFOCAL",
    "manufacturer": "CARE GROUP",
    "model": null,
    "aConstant": 118.4
  },
  {
    "id": "lens_magnus_toric_bifocal",
    "name": "MAGNUS TORIC BIFOCAL",
    "type": "TORIC",
    "manufacturer": "CARE GROUP",
    "model": null,
    "aConstant": null
  },
  {
    "id": "lens_acrivision_foreign_",
    "name": "ACRIVISION (FOREIGN)",
    "type": "MONOFOCAL",
    "manufacturer": "CARE GROUP",
    "model": null,
    "aConstant": 118.8
  },
  {
    "id": "lens_triphobic_hd_indian_yellow_trifocal_",
    "name": "TRIPHOBIC HD (INDIAN YELLOW TRIFOCAL)",
    "type": "TRIFOCAL",
    "manufacturer": "CARE GROUP",
    "model": null,
    "aConstant": 118.8
  },
  {
    "id": "lens_magnificent_indian_edof_",
    "name": "MAGNIFICENT (INDIAN EDOF)",
    "type": "EDOF",
    "manufacturer": "CARE GROUP",
    "model": null,
    "aConstant": 118.8
  },
  {
    "id": "lens_acrivision_trifocal_foreign_",
    "name": "ACRIVISION TRIFOCAL (FOREIGN)",
    "type": "TRIFOCAL",
    "manufacturer": "CARE GROUP",
    "model": null,
    "aConstant": 118.8
  },
  {
    "id": "lens_acriol_ec",
    "name": "ACRIOL EC",
    "type": "MONOFOCAL",
    "manufacturer": "CARE GROUP",
    "model": null,
    "aConstant": 118.8
  },
  {
    "id": "lens_acriol_clear",
    "name": "ACRIOL CLEAR",
    "type": "MONOFOCAL",
    "manufacturer": "CARE GROUP",
    "model": null,
    "aConstant": 118.8
  },
  {
    "id": "lens_acriol_ec_toric_monofocal_",
    "name": "ACRIOL EC TORIC (MONOFOCAL)",
    "type": "TORIC",
    "manufacturer": "CARE GROUP",
    "model": null,
    "aConstant": 118.8
  },
  {
    "id": "lens_autofocus_pro",
    "name": "AUTOFOCUS PRO",
    "type": "MONOFOCAL",
    "manufacturer": "OMNI GLOW",
    "model": null,
    "aConstant": 117.7
  },
  {
    "id": "lens_vivinex_impress_b_l",
    "name": "VIVINEX IMPRESS B&L",
    "type": "MONOFOCAL",
    "manufacturer": "HOYA",
    "model": null,
    "aConstant": 118.9
  }
]
