// Extracts the 29-lens IOL catalog from supabase/seed.sql into
// src/lib/demo-lens-catalog.ts (typed array used by the GitHub Pages demo seed).
import { readFileSync, writeFileSync } from 'fs'

const sql = readFileSync('supabase/seed.sql', 'utf8')
const re = /VALUES \('([^']*)', '([^']*)', '([^']*)', '([^']*)', (NULL|'[^']*'), (\d+(?:\.\d+)?|NULL), (\d+(?:\.\d+)?), (NULL|\d+(?:\.\d+)?), ('[^']*'|''),/g

type Row = {
  id: string; name: string; type: string; manufacturer: string
  model: string | null; aConstant: number | null
}

const rows: Row[] = []
let m: RegExpExecArray | null
while ((m = re.exec(sql)) !== null) {
  rows.push({
    id: m[1],
    name: m[2],
    type: m[3],
    manufacturer: m[4],
    model: m[5] === 'NULL' ? null : m[5].slice(1, -1),
    aConstant: m[6] === 'NULL' ? null : Number(m[6]),
  })
}

if (rows.length !== 29) {
  console.error(`Expected 29 catalog rows, parsed ${rows.length} — aborting`)
  process.exit(1)
}

const out = `// AUTO-GENERATED by scripts/gen-demo-catalog.ts — the clinic's real 29-lens
// IOL catalog (same data as supabase/seed.sql). Used only by the browser demo
// backend for the GitHub Pages deployment.
export type DemoLens = {
  id: string
  name: string
  type: string
  manufacturer: string
  model: string | null
  aConstant: number | null
}

export const DEMO_LENS_CATALOG: DemoLens[] = ${JSON.stringify(rows, null, 2)}
`
writeFileSync('src/lib/demo-lens-catalog.ts', out)
console.log(`Wrote ${rows.length} lens entries to src/lib/demo-lens-catalog.ts`)
